project:
  type: website
  output-dir: docs

website:
  title: "**Ohio Voters**"
  navbar:
    background: "#FFFFFF"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      

format:
  html:
    max-width: 300%
    theme:
      light: flatly
      # dark: darkly
    css: styles.css
    toc: false



